// AUTO-DERIVED from public/img — do not hand-edit the name union.
import {staticFile} from 'remotion';
import manifest from './images.json';

export type ImageName =
  | 'cuemix-badge'
  | 'e8-big-studio'
  | 'e8-black-hero'
  | 'e8-cuemix-home'
  | 'e8-ess-logo'
  | 'e8-footswitch'
  | 'e8-front-elev'
  | 'e8-front-elev-slim'
  | 'e8-fx-eq'
  | 'e8-fx-gate'
  | 'e8-fx-reverb'
  | 'e8-guitar-vox'
  | 'e8-ipad-hand'
  | 'e8-korg-synth'
  | 'e8-laptop-led'
  | 'e8-latency'
  | 'e8-lcd-a'
  | 'e8-lcd-b'
  | 'e8-line-in-insert'
  | 'e8-line-outs'
  | 'e8-loopback-menu'
  | 'e8-macbook-rack'
  | 'e8-mic-rack'
  | 'e8-mixer'
  | 'e8-mixer-phones'
  | 'e8-modular-wall'
  | 'e8-monitor-buttons'
  | 'e8-monitor-panel'
  | 'e8-optical-rear'
  | 'e8-rear-cabled'
  | 'e8-rear-digital'
  | 'e8-rear-elev'
  | 'e8-rear-elev-slim'
  | 'e8-render-34a'
  | 'e8-render-34b'
  | 'e8-render-rear-a'
  | 'e8-render-rear-b'
  | 'e8-spdif'
  | 'e8-sw-bigfish'
  | 'e8-sw-loopmasters'
  | 'e8-sw-lucid'
  | 'e8-sw-mosaic'
  | 'e8-sw-performer-a'
  | 'e8-sw-performer-b'
  | 'e8-sw-soundbank'
  | 'e8-usb-5gbps'
  | 'ul-amp-guitar'
  | 'ul-black-hero'
  | 'ul-cuemix-home'
  | 'ul-desk-hero'
  | 'ul-front-closeup'
  | 'ul-front-elev'
  | 'ul-fx-eq'
  | 'ul-fx-gate'
  | 'ul-fx-reverb'
  | 'ul-guitarist'
  | 'ul-ipad-cuemix'
  | 'ul-ipad-desk'
  | 'ul-latency'
  | 'ul-mixer'
  | 'ul-rack-ears'
  | 'ul-rack-kit'
  | 'ul-rear-elev'
  | 'ul-render-34'
  | 'ul-render-front'
  | 'ul-render-top'
  | 'ul-stack-laptop'
  | 'ul-system-diagram'
  | 'ul-wood-studio';

type Meta = {file: string; w: number; h: number; alpha: boolean; src: string};
const M = manifest as Record<ImageName, Meta>;

export const img = (n: ImageName): string => staticFile(`img/${M[n].file}`);
export const imgMeta = (n: ImageName): Meta => M[n];
export const imgAspect = (n: ImageName): number => M[n].w / M[n].h;
export const ALL_IMAGES = Object.keys(M) as ImageName[];
