"""Generate ASSET_COVERAGE.md: every distinct raw image mapped to its place in
the timeline, and a hard assertion that nothing was quietly dropped.

Master brief S2 requires this to be produced and checked before delivery, and
requires the count to come from the repository rather than from the brief.
"""
import json, os, re, sys

FPS = 30
BEAT = 0.447694 * FPS
def beatF(n): return round(n * BEAT)

RAW = '/home/user/motu-ultralitemk5-828'
pat = re.compile(r'^MOTU (828|UltraLite-mk5) \((\d+)\)\.(jpg|png)$')
raw = []
for f in sorted(os.listdir(RAW)):
    m = pat.match(f)
    if m:
        prod, num, ext = m.group(1), int(m.group(2)), m.group(3)
        raw.append((f, ('e828' if prod == '828' else 'ul') + f'_{num:02d}{ext[0]}'))
raw_slugs = {s for _, s in raw}

# walk the shot files in timeline order
order = ['coldOpen', 'ultralite', 'e828', 'close']
shots, b = [], 0.0
for mod in order:
    src = open(f'src/shots/{mod}.tsx').read()
    blocks = re.split(r"\n  \{\n    id: '", src)
    for blk in blocks[1:]:
        sid = blk[:blk.index("'")]
        beats = float(re.search(r"beats: ([\d.]+)", blk).group(1))
        slugs = re.findall(r"slug: '([a-z0-9_]+)'", blk)
        shots.append(dict(mod=mod, id=sid, beats=beats, start=b, slugs=slugs))
        b += beats

used, first_at = [], {}
for s in shots:
    s['f0'], s['f1'] = beatF(s['start']), beatF(s['start'] + s['beats'])
    for sl in s['slugs']:
        used.append(sl)
        first_at.setdefault(sl, s)

missing = sorted(raw_slugs - set(used))
unknown = sorted(set(used) - raw_slugs)

MOV = {'coldOpen': 'Cold open', 'ultralite': 'MOTU UltraLite-mk5', 'e828': 'MOTU 828', 'close': 'Close'}
lines = []
w = lines.append
w('# Asset coverage — MOTU camera-motion reel (`reel4k/`)\n')
w('Generated by `tools/coverage.py`. This file is the master brief S2 check:')
w('every distinct raw product image at the repository root, mapped to where it')
w('appears in the 90.7-second timeline.\n')
w('## The count\n')
w('The same-numbered `.jpg` and `.png` at the repository root are **not two')
w('encodings of one photograph** — they are different pictures. `MOTU')
w('UltraLite-mk5 (1).jpg` is a lifestyle photograph; `MOTU UltraLite-mk5 (1).png`')
w('is a software screen. Every pair was inspected before this list was built,')
w('which is why the distinct-shot count is **69**, not the 45 a jpg/png-pairing')
w('assumption would give.\n')
n828 = sum(1 for s in raw_slugs if s.startswith('e828'))
nul = len(raw_slugs) - n828
w(f'| | count |\n|---|---|\n| MOTU 828 | {n828} |\n| MOTU UltraLite-mk5 | {nul} |\n| **total distinct raw images** | **{len(raw_slugs)}** |\n')
w('## Coverage\n')
w(f'- images placed in the timeline: **{len(set(used))} / {len(raw_slugs)}**')
w(f'- images never shown: **{len(missing)}**' + (' — ' + ', '.join(missing) if missing else ' ✅'))
if unknown:
    w(f'- referenced but not a raw file: {", ".join(unknown)} ⚠️')
w('')
w('## Map\n')
w('| image | source file | product | first appearance | shot | movement |')
w('|---|---|---|---|---|---|')
for f, sl in raw:
    s = first_at.get(sl)
    if not s:
        w(f'| `{sl}` | {f} | | **NOT USED** | | |'); continue
    t = s['f0'] / FPS
    w(f"| `{sl}` | {f} | {'828' if sl.startswith('e828') else 'UltraLite-mk5'} | "
      f"{int(t//60)}:{t%60:05.2f} (f{s['f0']}) | `{s['id']}` | {MOV[s['mod']]} |")
w('')
w('## Shot list\n')
w('| # | shot | movement | beats | frames | seconds | images |')
w('|---|---|---|---|---|---|---|')
for i, s in enumerate(shots, 1):
    w(f"| {i} | `{s['id']}` | {MOV[s['mod']]} | {s['beats']:g} | {s['f0']}–{s['f1']} | "
      f"{s['f0']/FPS:.2f}–{s['f1']/FPS:.2f} | {', '.join('`'+x+'`' for x in s['slugs']) or '—'} |")
w('')
open('ASSET_COVERAGE.md', 'w').write('\n'.join(lines) + '\n')

print(f"raw distinct images : {len(raw_slugs)}  (828={n828}, UltraLite={nul})")
print(f"placed in timeline  : {len(set(used))}")
print(f"total placements    : {len(used)} (some images appear more than once)")
print(f"shots               : {len(shots)}, total beats {b:g}")
if missing or unknown:
    print("FAIL: missing", missing, "unknown", unknown); sys.exit(1)
print("COVERAGE COMPLETE - every distinct raw image appears in the reel.")
