// GENERATED by scripts/prep_assets.py — do not edit by hand.
// Every size and every bounding box here was measured off the file on disk.

import type { Asset, Clip } from "./assets.ts";

export const ASSETS: Asset[] = [
 {
  "slug": "cuemix-eq",
  "file": "img/cuemix-eq.webp",
  "kind": "photo",
  "model": 0,
  "w": 1081,
  "h": 609,
  "ar": 1.775,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "cuemix-mark",
  "file": "img/cuemix-mark.png",
  "kind": "mark",
  "model": 0,
  "w": 1024,
  "h": 1024,
  "ar": 1.0,
  "bbox": [
   0.0225,
   0.0225,
   0.9775,
   0.9775
  ],
  "transparent": true
 },
 {
  "slug": "cuemix-mix",
  "file": "img/cuemix-mix.webp",
  "kind": "photo",
  "model": 0,
  "w": 2153,
  "h": 1213,
  "ar": 1.7749,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "cuemix-strip",
  "file": "img/cuemix-strip.webp",
  "kind": "photo",
  "model": 0,
  "w": 2160,
  "h": 1216,
  "ar": 1.7763,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "cuemix-verb",
  "file": "img/cuemix-verb.webp",
  "kind": "photo",
  "model": 0,
  "w": 2160,
  "h": 1215,
  "ar": 1.7778,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-3q",
  "file": "img/e8-3q.png",
  "kind": "hero",
  "model": 8,
  "w": 3000,
  "h": 733,
  "ar": 4.0928,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-3q-left",
  "file": "img/e8-3q-left.png",
  "kind": "hero",
  "model": 8,
  "w": 3000,
  "h": 769,
  "ar": 3.9012,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-back-3q",
  "file": "img/e8-back-3q.png",
  "kind": "hero",
  "model": 8,
  "w": 3000,
  "h": 717,
  "ar": 4.1841,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-back-hi",
  "file": "img/e8-back-hi.png",
  "kind": "hero",
  "model": 8,
  "w": 3000,
  "h": 746,
  "ar": 4.0214,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-black",
  "file": "img/e8-black.webp",
  "kind": "photo",
  "model": 8,
  "w": 3839,
  "h": 1749,
  "ar": 2.195,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-console",
  "file": "img/e8-console.webp",
  "kind": "photo",
  "model": 0,
  "w": 2000,
  "h": 1532,
  "ar": 1.3055,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-desk",
  "file": "img/e8-desk.webp",
  "kind": "photo",
  "model": 8,
  "w": 2880,
  "h": 834,
  "ar": 3.4532,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-foot",
  "file": "img/e8-foot.webp",
  "kind": "photo",
  "model": 8,
  "w": 509,
  "h": 417,
  "ar": 1.2206,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-front",
  "file": "img/e8-front.png",
  "kind": "panel",
  "model": 8,
  "w": 3000,
  "h": 272,
  "ar": 11.0294,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-front-3q",
  "file": "img/e8-front-3q.png",
  "kind": "panel",
  "model": 8,
  "w": 3000,
  "h": 465,
  "ar": 6.4516,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-group",
  "file": "img/e8-group.webp",
  "kind": "photo",
  "model": 8,
  "w": 2000,
  "h": 714,
  "ar": 2.8011,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-guitar",
  "file": "img/e8-guitar.webp",
  "kind": "photo",
  "model": 0,
  "w": 2500,
  "h": 1732,
  "ar": 1.4434,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-insert",
  "file": "img/e8-insert.webp",
  "kind": "photo",
  "model": 8,
  "w": 1038,
  "h": 629,
  "ar": 1.6502,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-laptop",
  "file": "img/e8-laptop.webp",
  "kind": "photo",
  "model": 8,
  "w": 2509,
  "h": 2166,
  "ar": 1.1584,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-lineout",
  "file": "img/e8-lineout.webp",
  "kind": "photo",
  "model": 8,
  "w": 2000,
  "h": 891,
  "ar": 2.2447,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-loopback",
  "file": "img/e8-loopback.webp",
  "kind": "photo",
  "model": 8,
  "w": 768,
  "h": 768,
  "ar": 1.0,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-meter",
  "file": "img/e8-meter.webp",
  "kind": "photo",
  "model": 8,
  "w": 1522,
  "h": 485,
  "ar": 3.1381,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-meters",
  "file": "img/e8-meters.webp",
  "kind": "photo",
  "model": 8,
  "w": 2000,
  "h": 1083,
  "ar": 1.8467,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-mic",
  "file": "img/e8-mic.webp",
  "kind": "photo",
  "model": 0,
  "w": 2000,
  "h": 1029,
  "ar": 1.9436,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-monitor",
  "file": "img/e8-monitor.webp",
  "kind": "photo",
  "model": 8,
  "w": 423,
  "h": 481,
  "ar": 0.8794,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-optical",
  "file": "img/e8-optical.webp",
  "kind": "photo",
  "model": 8,
  "w": 768,
  "h": 456,
  "ar": 1.6842,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-rack",
  "file": "img/e8-rack.webp",
  "kind": "photo",
  "model": 8,
  "w": 4000,
  "h": 1845,
  "ar": 2.168,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-rear",
  "file": "img/e8-rear.png",
  "kind": "panel",
  "model": 8,
  "w": 3000,
  "h": 298,
  "ar": 10.0671,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-rear-3q",
  "file": "img/e8-rear-3q.png",
  "kind": "panel",
  "model": 8,
  "w": 3000,
  "h": 505,
  "ar": 5.9406,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "e8-rearopt",
  "file": "img/e8-rearopt.webp",
  "kind": "photo",
  "model": 8,
  "w": 2000,
  "h": 1083,
  "ar": 1.8467,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-spdif",
  "file": "img/e8-spdif.webp",
  "kind": "photo",
  "model": 8,
  "w": 576,
  "h": 497,
  "ar": 1.159,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-studio",
  "file": "img/e8-studio.webp",
  "kind": "photo",
  "model": 8,
  "w": 1000,
  "h": 519,
  "ar": 1.9268,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "e8-synth",
  "file": "img/e8-synth.webp",
  "kind": "photo",
  "model": 0,
  "w": 576,
  "h": 425,
  "ar": 1.3553,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ess-mark",
  "file": "img/ess-mark.webp",
  "kind": "mark",
  "model": 0,
  "w": 1787,
  "h": 941,
  "ar": 1.899,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "motu-logo",
  "file": "img/motu-logo.png",
  "kind": "logo",
  "model": 0,
  "w": 2390,
  "h": 946,
  "ar": 3.1548,
  "bbox": [
   0.0088,
   0.1068,
   0.9908,
   0.8932
  ],
  "transparent": true
 },
 {
  "slug": "shivansh-logo",
  "file": "img/shivansh-logo.png",
  "kind": "logo",
  "model": 0,
  "w": 2372,
  "h": 714,
  "ar": 3.3221,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "ul-3q",
  "file": "img/ul-3q.png",
  "kind": "hero",
  "model": 5,
  "w": 4138,
  "h": 2331,
  "ar": 2.3788,
  "bbox": [
   0.0213,
   0.2866,
   0.9135,
   0.9524
  ],
  "transparent": true
 },
 {
  "slug": "ul-3q-high",
  "file": "img/ul-3q-high.png",
  "kind": "hero",
  "model": 5,
  "w": 5000,
  "h": 3127,
  "ar": 1.9647,
  "bbox": [
   0.0428,
   0.1964,
   0.956,
   0.9396
  ],
  "transparent": true
 },
 {
  "slug": "ul-3q-left",
  "file": "img/ul-3q-left.png",
  "kind": "hero",
  "model": 5,
  "w": 4938,
  "h": 2532,
  "ar": 2.5116,
  "bbox": [
   0.0294,
   0.1718,
   0.9708,
   0.9028
  ],
  "transparent": true
 },
 {
  "slug": "ul-amp",
  "file": "img/ul-amp.webp",
  "kind": "photo",
  "model": 5,
  "w": 3768,
  "h": 2438,
  "ar": 1.5455,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-black",
  "file": "img/ul-black.webp",
  "kind": "photo",
  "model": 5,
  "w": 3839,
  "h": 2336,
  "ar": 1.6434,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-desk",
  "file": "img/ul-desk.webp",
  "kind": "photo",
  "model": 5,
  "w": 4135,
  "h": 2848,
  "ar": 1.4519,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-face",
  "file": "img/ul-face.png",
  "kind": "panel",
  "model": 5,
  "w": 2200,
  "h": 1000,
  "ar": 2.2,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "ul-front",
  "file": "img/ul-front.png",
  "kind": "panel",
  "model": 5,
  "w": 3682,
  "h": 726,
  "ar": 5.0716,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "ul-glow",
  "file": "img/ul-glow.webp",
  "kind": "photo",
  "model": 5,
  "w": 3263,
  "h": 2098,
  "ar": 1.5553,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-ipad",
  "file": "img/ul-ipad.webp",
  "kind": "photo",
  "model": 5,
  "w": 4371,
  "h": 2606,
  "ar": 1.6773,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-laptop",
  "file": "img/ul-laptop.webp",
  "kind": "photo",
  "model": 5,
  "w": 3839,
  "h": 2336,
  "ar": 1.6434,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-latency",
  "file": "img/ul-latency.webp",
  "kind": "photo",
  "model": 5,
  "w": 4000,
  "h": 2754,
  "ar": 1.4524,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-rear",
  "file": "img/ul-rear.png",
  "kind": "panel",
  "model": 5,
  "w": 3682,
  "h": 729,
  "ar": 5.0508,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": true
 },
 {
  "slug": "ul-room",
  "file": "img/ul-room.webp",
  "kind": "photo",
  "model": 5,
  "w": 4805,
  "h": 3210,
  "ar": 1.4969,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "ul-routing",
  "file": "img/ul-routing.webp",
  "kind": "photo",
  "model": 5,
  "w": 1726,
  "h": 835,
  "ar": 2.7208,
  "bbox": [
   0.0388,
   0.1437,
   0.9594,
   0.8431
  ],
  "transparent": false
 },
 {
  "slug": "ul-white",
  "file": "img/ul-white.webp",
  "kind": "photo",
  "model": 5,
  "w": 2560,
  "h": 1656,
  "ar": 1.5459,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 },
 {
  "slug": "usb-mark",
  "file": "img/usb-mark.webp",
  "kind": "mark",
  "model": 0,
  "w": 1787,
  "h": 941,
  "ar": 1.899,
  "bbox": [
   0.0,
   0.0,
   1.0,
   1.0
  ],
  "transparent": false
 }
];

export const CLIPS: Clip[] = [
 {
  "slug": "clip-11-ul-desk",
  "file": "broll/clip-11-ul-desk.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 },
 {
  "slug": "clip-12-ul-road",
  "file": "broll/clip-12-ul-road.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 },
 {
  "slug": "clip-13-ul-guitar",
  "file": "broll/clip-13-ul-guitar.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 },
 {
  "slug": "clip-14-ul-stage",
  "file": "broll/clip-14-ul-stage.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 },
 {
  "slug": "clip-15-e8-control",
  "file": "broll/clip-15-e8-control.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 },
 {
  "slug": "clip-16-e8-stream",
  "file": "broll/clip-16-e8-stream.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 },
 {
  "slug": "clip-17-e8-tracking",
  "file": "broll/clip-17-e8-tracking.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 },
 {
  "slug": "clip-18-both-studio",
  "file": "broll/clip-18-both-studio.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.5581,
  "dur": 5.04
 }
];

export const REGION_LUM: Record<string, number> = {
 "ul.inputs": 0.2353,
 "ul.phones": 0.2193,
 "ul.gain": 0.2184,
 "ul.meter": 0.2614,
 "ul.power": 0.2067,
 "ul.midi": 0.2237,
 "ul.optical": 0.1778,
 "ul.spdif": 0.3091,
 "ul.lineout": 0.2653,
 "ul.linein": 0.2612,
 "ul.face": 0.1806,
 "ul.oled": 0.2318
};
