// Branding-cadence audit (Section 11 checkpoint 7).
//
// Emits a timestamped list of every Shivansh Electronics and MOTU appearance,
// checks the gap guideline, and confirms www.shivanshelectronics.in reads as
// the most-repeated single element on screen.
//
// Guidelines scaled from the approved AVB cadence:
//   AVB long-form  898 s -> 45 Shivansh / 8 MOTU, longest gap 24 s (<= 40 s)
//   this long-form 598 s -> proportionally ~30 Shivansh / ~5 MOTU, <= 40 s
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const S = JSON.parse(fs.readFileSync(path.resolve(__dirname, "..", "src", "schedule.json"), "utf8"));
const FPS = S.fps;
const GAP_LIMIT = 40;

const ts = (f) => {
  const s = f / FPS;
  return `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(Math.floor(s % 60)).padStart(2, "0")}`;
};

// Which forms each beat kind puts on screen.
const shivanshForm = (b) => {
  if (b.kind === "brandBeat") return "full branding beat (logo + role + region + URL" + (b.socials ? " + socials)" : ")");
  if (b.kind === "contactBeat") return "contact panel (logo + role + URL + best-price + socials)";
  if (b.kind === "outro") return "outro lockup (both logos + both prices + URL + socials)";
  if (b.kind === "priceBeat") return "price beat (dual price + logo + URL)";
  if (b.kind === "statement" && b.brand === "beat") return "statement lockup (logo + URL)";
  if (b.brand === "corner") return "corner logo + URL";
  if (b.brand === "lower") return "lower-third logo + URL + region";
  return null;
};
const hasMotu = (b) =>
  Boolean(b.motu) || b.kind === "outro" ||
  (b.kind === "brandBeat" && b.motu !== false);

const shiv = [], motu = [], urlBeats = [];
for (const b of S.beats) {
  const form = shivanshForm(b);
  if (form) {
    shiv.push({ inF: b.from, outF: b.from + b.durationInFrames, ch: b.chapter, id: b.id, form });
    urlBeats.push(b.id);
  }
  if (hasMotu(b)) motu.push({ inF: b.from, outF: b.from + b.durationInFrames, ch: b.chapter, id: b.id });
}

const gaps = [];
for (let i = 1; i < shiv.length; i++) gaps.push((shiv[i].inF - shiv[i - 1].outF) / FPS);
const lead = shiv.length ? shiv[0].inF / FPS : Infinity;
const trail = shiv.length ? (S.durationInFrames - shiv[shiv.length - 1].outF) / FPS : Infinity;
const worst = Math.max(lead, trail, ...(gaps.length ? gaps : [0]));

const lines = [];
lines.push(`# Branding cadence — MOTU UltraLite-mk5 & 828 long-form (${S.durationInSeconds}s)`);
lines.push("");
lines.push("Generated by `npm run branding` from the same schedule that renders the video.");
lines.push("");
lines.push("Every logo appearance renders through the `Logo` component, which draws the");
lines.push("supplied file exactly as given — **directly on the video, with no box, card or");
lines.push("plate**. Both supplied logos carry their own opaque white rounded-rect ground, so");
lines.push("the page is held in a near-white range and full-bleed media scenes place a");
lines.push("page-level band behind the branding row, which is why that ground always reads as");
lines.push("continuous with the picture rather than as artwork on a plate.");
lines.push("");
lines.push(`## Shivansh Electronics — ${shiv.length} appearances (longest gap ${worst.toFixed(0)}s, guideline <= ${GAP_LIMIT}s)`);
lines.push("");
lines.push("| In | Out | Chapter | Beat | Form |");
lines.push("|---|---|---|---|---|");
for (const a of shiv) lines.push(`| ${ts(a.inF)} | ${ts(a.outF)} | ${a.ch} | \`${a.id}\` | ${a.form} |`);
lines.push("");
lines.push(`## MOTU — ${motu.length} appearances`);
lines.push("");
lines.push("| In | Out | Chapter | Beat |");
lines.push("|---|---|---|---|");
for (const a of motu) lines.push(`| ${ts(a.inF)} | ${ts(a.outF)} | ${a.ch} | \`${a.id}\` |`);
lines.push("");
lines.push("## Result");
lines.push("");
lines.push(`- Shivansh Electronics : **${shiv.length}** appearances`);
lines.push(`- MOTU                 : **${motu.length}** appearances (${(shiv.length / motu.length).toFixed(1)}x less frequent, as required)`);
lines.push(`- Longest gap between Shivansh appearances: **${worst.toFixed(0)}s** (guideline <= ${GAP_LIMIT}s)`);
lines.push(`- Lead-in gap: **${lead.toFixed(0)}s** · trailing gap to end of video: **${trail.toFixed(0)}s**`);
const chs = new Set(shiv.map((a) => a.ch));
lines.push(`- Chapters containing a Shivansh beat: **${chs.size}/${S.chapters.length}**`);
lines.push(`- \`www.shivanshelectronics.in\` on screen: **${urlBeats.length}** beats — more than any other single contact detail`);

fs.writeFileSync(path.resolve(__dirname, "..", "BRANDING_CADENCE.md"), lines.join("\n") + "\n");

console.log(`Shivansh : ${shiv.length}  MOTU: ${motu.length}  ratio ${(shiv.length / motu.length).toFixed(1)}x`);
console.log(`longest gap ${worst.toFixed(1)}s (lead ${lead.toFixed(1)}s, trail ${trail.toFixed(1)}s) — limit ${GAP_LIMIT}s`);
console.log(`chapters covered ${chs.size}/${S.chapters.length}`);
if (worst > GAP_LIMIT) { console.error("FAIL: gap exceeds guideline"); process.exit(1); }
if (motu.length >= shiv.length) { console.error("FAIL: MOTU must appear less often than Shivansh"); process.exit(1); }
console.log("OK");
