// AUTO-GENERATED by scripts/prep-assets.mjs — do not edit by hand.
// 69 distinct product photographs, re-exported from the originals in
// the repository root at up to 3840 px on the long edge. The slug, the source
// mapping and the duplicate reconciliation are inherited from
// src/lib/images.json, the curation this repository's earlier deliverables made.
//
// kind:    cutout (transparent) | strip (transparent ultra-wide panel run) | panel (opaque ultra-wide) | photo
// subject: hardware | detail | context | ui | diagram | mark | bundle
// `covers` lists the original repository filename this image came from.

export type AssetKind = "cutout" | "strip" | "panel" | "photo";
export type AssetSubject = "hardware" | "detail" | "context" | "ui" | "diagram" | "mark" | "bundle";
export type ProductKey = "pul" | "p828" | "shared";

export type Asset = {
  slug: string;
  file: string;
  /** A 512 px copy, for the darkened wash behind a full-bleed shot. */
  bg: string;
  product: ProductKey;
  w: number;
  h: number;
  ar: number;
  kind: AssetKind;
  subject: AssetSubject;
  alpha: boolean;
  covers: string[];
};

export const ASSETS: Asset[] = [
 {
  "slug": "e8-big-studio",
  "file": "e8-big-studio.jpg",
  "bg": "bg/e8-big-studio.jpg",
  "product": "p828",
  "w": 1000,
  "h": 519,
  "ar": 1.927,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (30).jpg"
  ]
 },
 {
  "slug": "e8-black-hero",
  "file": "e8-black-hero.jpg",
  "bg": "bg/e8-black-hero.jpg",
  "product": "p828",
  "w": 3839,
  "h": 1749,
  "ar": 2.195,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 828 (6).jpg"
  ]
 },
 {
  "slug": "e8-footswitch",
  "file": "e8-footswitch.jpg",
  "bg": "bg/e8-footswitch.jpg",
  "product": "p828",
  "w": 509,
  "h": 417,
  "ar": 1.221,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (20).jpg"
  ]
 },
 {
  "slug": "e8-front-elev",
  "file": "e8-front-elev.png",
  "bg": "bg/e8-front-elev.jpg",
  "product": "p828",
  "w": 3000,
  "h": 465,
  "ar": 6.452,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (3).png"
  ]
 },
 {
  "slug": "e8-front-elev-slim",
  "file": "e8-front-elev-slim.png",
  "bg": "bg/e8-front-elev-slim.jpg",
  "product": "p828",
  "w": 3000,
  "h": 272,
  "ar": 11.029,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (4).png"
  ]
 },
 {
  "slug": "e8-guitar-vox",
  "file": "e8-guitar-vox.jpg",
  "bg": "bg/e8-guitar-vox.jpg",
  "product": "p828",
  "w": 2500,
  "h": 1732,
  "ar": 1.443,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (18).jpg"
  ]
 },
 {
  "slug": "e8-ipad-hand",
  "file": "e8-ipad-hand.png",
  "bg": "bg/e8-ipad-hand.jpg",
  "product": "p828",
  "w": 948,
  "h": 512,
  "ar": 1.852,
  "kind": "cutout",
  "subject": "context",
  "alpha": true,
  "covers": [
   "MOTU 828 (15).png"
  ]
 },
 {
  "slug": "e8-korg-synth",
  "file": "e8-korg-synth.jpg",
  "bg": "bg/e8-korg-synth.jpg",
  "product": "p828",
  "w": 576,
  "h": 425,
  "ar": 1.355,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (26).jpg"
  ]
 },
 {
  "slug": "e8-laptop-led",
  "file": "e8-laptop-led.jpg",
  "bg": "bg/e8-laptop-led.jpg",
  "product": "p828",
  "w": 3840,
  "h": 1772,
  "ar": 2.167,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (21).jpg"
  ]
 },
 {
  "slug": "e8-latency",
  "file": "e8-latency.png",
  "bg": "bg/e8-latency.jpg",
  "product": "p828",
  "w": 815,
  "h": 276,
  "ar": 2.953,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 828 (14).png"
  ]
 },
 {
  "slug": "e8-lcd-a",
  "file": "e8-lcd-a.jpg",
  "bg": "bg/e8-lcd-a.jpg",
  "product": "p828",
  "w": 1522,
  "h": 485,
  "ar": 3.138,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (3).jpg"
  ]
 },
 {
  "slug": "e8-lcd-b",
  "file": "e8-lcd-b.jpg",
  "bg": "bg/e8-lcd-b.jpg",
  "product": "p828",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (7).jpg"
  ]
 },
 {
  "slug": "e8-line-in-insert",
  "file": "e8-line-in-insert.jpg",
  "bg": "bg/e8-line-in-insert.jpg",
  "product": "p828",
  "w": 1038,
  "h": 629,
  "ar": 1.65,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (22).jpg"
  ]
 },
 {
  "slug": "e8-line-outs",
  "file": "e8-line-outs.jpg",
  "bg": "bg/e8-line-outs.jpg",
  "product": "p828",
  "w": 2000,
  "h": 891,
  "ar": 2.245,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (1).jpg"
  ]
 },
 {
  "slug": "e8-loopback-menu",
  "file": "e8-loopback-menu.jpg",
  "bg": "bg/e8-loopback-menu.jpg",
  "product": "p828",
  "w": 768,
  "h": 768,
  "ar": 1,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (2).jpg"
  ]
 },
 {
  "slug": "e8-macbook-rack",
  "file": "e8-macbook-rack.jpg",
  "bg": "bg/e8-macbook-rack.jpg",
  "product": "p828",
  "w": 2509,
  "h": 2166,
  "ar": 1.158,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (28).jpg"
  ]
 },
 {
  "slug": "e8-mic-rack",
  "file": "e8-mic-rack.jpg",
  "bg": "bg/e8-mic-rack.jpg",
  "product": "p828",
  "w": 2000,
  "h": 1029,
  "ar": 1.944,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (25).jpg"
  ]
 },
 {
  "slug": "e8-modular-wall",
  "file": "e8-modular-wall.jpg",
  "bg": "bg/e8-modular-wall.jpg",
  "product": "p828",
  "w": 2000,
  "h": 1532,
  "ar": 1.305,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (11).jpg"
  ]
 },
 {
  "slug": "e8-monitor-buttons",
  "file": "e8-monitor-buttons.jpg",
  "bg": "bg/e8-monitor-buttons.jpg",
  "product": "p828",
  "w": 423,
  "h": 481,
  "ar": 0.879,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (9).jpg"
  ]
 },
 {
  "slug": "e8-monitor-panel",
  "file": "e8-monitor-panel.jpg",
  "bg": "bg/e8-monitor-panel.jpg",
  "product": "p828",
  "w": 2000,
  "h": 714,
  "ar": 2.801,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (27).jpg"
  ]
 },
 {
  "slug": "e8-optical-rear",
  "file": "e8-optical-rear.jpg",
  "bg": "bg/e8-optical-rear.jpg",
  "product": "p828",
  "w": 768,
  "h": 456,
  "ar": 1.684,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (4).jpg"
  ]
 },
 {
  "slug": "e8-rear-cabled",
  "file": "e8-rear-cabled.png",
  "bg": "bg/e8-rear-cabled.jpg",
  "product": "p828",
  "w": 1900,
  "h": 821,
  "ar": 2.314,
  "kind": "cutout",
  "subject": "detail",
  "alpha": true,
  "covers": [
   "MOTU 828 (13).png"
  ]
 },
 {
  "slug": "e8-rear-digital",
  "file": "e8-rear-digital.jpg",
  "bg": "bg/e8-rear-digital.jpg",
  "product": "p828",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (10).jpg"
  ]
 },
 {
  "slug": "e8-rear-elev",
  "file": "e8-rear-elev.png",
  "bg": "bg/e8-rear-elev.jpg",
  "product": "p828",
  "w": 3000,
  "h": 505,
  "ar": 5.941,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (7).png"
  ]
 },
 {
  "slug": "e8-rear-elev-slim",
  "file": "e8-rear-elev-slim.png",
  "bg": "bg/e8-rear-elev-slim.jpg",
  "product": "p828",
  "w": 3000,
  "h": 298,
  "ar": 10.067,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (8).png"
  ]
 },
 {
  "slug": "e8-render-34a",
  "file": "e8-render-34a.png",
  "bg": "bg/e8-render-34a.jpg",
  "product": "p828",
  "w": 3000,
  "h": 733,
  "ar": 4.093,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (1).png"
  ]
 },
 {
  "slug": "e8-render-34b",
  "file": "e8-render-34b.png",
  "bg": "bg/e8-render-34b.jpg",
  "product": "p828",
  "w": 3000,
  "h": 769,
  "ar": 3.901,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (2).png"
  ]
 },
 {
  "slug": "e8-render-rear-a",
  "file": "e8-render-rear-a.png",
  "bg": "bg/e8-render-rear-a.jpg",
  "product": "p828",
  "w": 3000,
  "h": 717,
  "ar": 4.184,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (5).png"
  ]
 },
 {
  "slug": "e8-render-rear-b",
  "file": "e8-render-rear-b.png",
  "bg": "bg/e8-render-rear-b.jpg",
  "product": "p828",
  "w": 3000,
  "h": 746,
  "ar": 4.021,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (6).png"
  ]
 },
 {
  "slug": "e8-spdif",
  "file": "e8-spdif.jpg",
  "bg": "bg/e8-spdif.jpg",
  "product": "p828",
  "w": 576,
  "h": 497,
  "ar": 1.159,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (5).jpg"
  ]
 },
 {
  "slug": "e8-sw-bigfish",
  "file": "e8-sw-bigfish.jpg",
  "bg": "bg/e8-sw-bigfish.jpg",
  "product": "p828",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (8).jpg"
  ]
 },
 {
  "slug": "e8-sw-loopmasters",
  "file": "e8-sw-loopmasters.jpg",
  "bg": "bg/e8-sw-loopmasters.jpg",
  "product": "p828",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (23).jpg"
  ]
 },
 {
  "slug": "e8-sw-lucid",
  "file": "e8-sw-lucid.jpg",
  "bg": "bg/e8-sw-lucid.jpg",
  "product": "p828",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (24).jpg"
  ]
 },
 {
  "slug": "e8-sw-mosaic",
  "file": "e8-sw-mosaic.jpg",
  "bg": "bg/e8-sw-mosaic.jpg",
  "product": "p828",
  "w": 2880,
  "h": 834,
  "ar": 3.453,
  "kind": "panel",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (29).jpg"
  ]
 },
 {
  "slug": "e8-sw-performer-a",
  "file": "e8-sw-performer-a.png",
  "bg": "bg/e8-sw-performer-a.jpg",
  "product": "p828",
  "w": 2562,
  "h": 1513,
  "ar": 1.693,
  "kind": "cutout",
  "subject": "bundle",
  "alpha": true,
  "covers": [
   "MOTU 828 (11).png"
  ]
 },
 {
  "slug": "e8-sw-performer-b",
  "file": "e8-sw-performer-b.png",
  "bg": "bg/e8-sw-performer-b.jpg",
  "product": "p828",
  "w": 2880,
  "h": 1711,
  "ar": 1.683,
  "kind": "cutout",
  "subject": "bundle",
  "alpha": true,
  "covers": [
   "MOTU 828 (12).png"
  ]
 },
 {
  "slug": "e8-sw-soundbank",
  "file": "e8-sw-soundbank.png",
  "bg": "bg/e8-sw-soundbank.jpg",
  "product": "p828",
  "w": 1678,
  "h": 948,
  "ar": 1.77,
  "kind": "cutout",
  "subject": "bundle",
  "alpha": true,
  "covers": [
   "MOTU 828 (10).png"
  ]
 },
 {
  "slug": "ul-amp-guitar",
  "file": "ul-amp-guitar.jpg",
  "bg": "bg/ul-amp-guitar.jpg",
  "product": "pul",
  "w": 3768,
  "h": 2438,
  "ar": 1.546,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (3).jpg"
  ]
 },
 {
  "slug": "ul-black-hero",
  "file": "ul-black-hero.jpg",
  "bg": "bg/ul-black-hero.jpg",
  "product": "pul",
  "w": 3839,
  "h": 2336,
  "ar": 1.643,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (11).jpg"
  ]
 },
 {
  "slug": "ul-desk-hero",
  "file": "ul-desk-hero.jpg",
  "bg": "bg/ul-desk-hero.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2644,
  "ar": 1.452,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (1).jpg"
  ]
 },
 {
  "slug": "ul-front-closeup",
  "file": "ul-front-closeup.png",
  "bg": "bg/ul-front-closeup.jpg",
  "product": "pul",
  "w": 2200,
  "h": 1000,
  "ar": 2.2,
  "kind": "cutout",
  "subject": "detail",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (2).png"
  ]
 },
 {
  "slug": "ul-front-elev",
  "file": "ul-front-elev.png",
  "bg": "bg/ul-front-elev.jpg",
  "product": "pul",
  "w": 3682,
  "h": 726,
  "ar": 5.072,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (8).png"
  ]
 },
 {
  "slug": "ul-guitarist",
  "file": "ul-guitarist.jpg",
  "bg": "bg/ul-guitarist.jpg",
  "product": "pul",
  "w": 2560,
  "h": 1656,
  "ar": 1.546,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (12).jpg"
  ]
 },
 {
  "slug": "ul-ipad-cuemix",
  "file": "ul-ipad-cuemix.jpg",
  "bg": "bg/ul-ipad-cuemix.jpg",
  "product": "pul",
  "w": 3263,
  "h": 2098,
  "ar": 1.555,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (13).jpg"
  ]
 },
 {
  "slug": "ul-ipad-desk",
  "file": "ul-ipad-desk.jpg",
  "bg": "bg/ul-ipad-desk.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2290,
  "ar": 1.677,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (4).jpg"
  ]
 },
 {
  "slug": "ul-latency",
  "file": "ul-latency.jpg",
  "bg": "bg/ul-latency.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2644,
  "ar": 1.452,
  "kind": "photo",
  "subject": "diagram",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (10).jpg"
  ]
 },
 {
  "slug": "ul-rack-ears",
  "file": "ul-rack-ears.png",
  "bg": "bg/ul-rack-ears.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2688,
  "ar": 1.429,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (4).png"
  ]
 },
 {
  "slug": "ul-rack-kit",
  "file": "ul-rack-kit.png",
  "bg": "bg/ul-rack-kit.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2688,
  "ar": 1.429,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (5).png"
  ]
 },
 {
  "slug": "ul-rear-elev",
  "file": "ul-rear-elev.png",
  "bg": "bg/ul-rear-elev.jpg",
  "product": "pul",
  "w": 3682,
  "h": 729,
  "ar": 5.051,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (9).png"
  ]
 },
 {
  "slug": "ul-render-34",
  "file": "ul-render-34.png",
  "bg": "bg/ul-render-34.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2164,
  "ar": 1.774,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (3).png"
  ]
 },
 {
  "slug": "ul-render-front",
  "file": "ul-render-front.png",
  "bg": "bg/ul-render-front.jpg",
  "product": "pul",
  "w": 3840,
  "h": 1968,
  "ar": 1.951,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (6).png"
  ]
 },
 {
  "slug": "ul-render-top",
  "file": "ul-render-top.png",
  "bg": "bg/ul-render-top.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2402,
  "ar": 1.599,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (7).png"
  ]
 },
 {
  "slug": "ul-stack-laptop",
  "file": "ul-stack-laptop.jpg",
  "bg": "bg/ul-stack-laptop.jpg",
  "product": "pul",
  "w": 3839,
  "h": 2336,
  "ar": 1.643,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (2).jpg"
  ]
 },
 {
  "slug": "ul-system-diagram",
  "file": "ul-system-diagram.jpg",
  "bg": "bg/ul-system-diagram.jpg",
  "product": "pul",
  "w": 1726,
  "h": 835,
  "ar": 2.067,
  "kind": "photo",
  "subject": "diagram",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (14).jpg"
  ]
 },
 {
  "slug": "ul-wood-studio",
  "file": "ul-wood-studio.jpg",
  "bg": "bg/ul-wood-studio.jpg",
  "product": "pul",
  "w": 3840,
  "h": 2566,
  "ar": 1.496,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (5).jpg"
  ]
 },
 {
  "slug": "cuemix-badge",
  "file": "cuemix-badge.png",
  "bg": "bg/cuemix-badge.jpg",
  "product": "shared",
  "w": 1024,
  "h": 1024,
  "ar": 1,
  "kind": "cutout",
  "subject": "mark",
  "alpha": true,
  "covers": [
   "MOTU 828 (9).png"
  ]
 },
 {
  "slug": "e8-cuemix-home",
  "file": "e8-cuemix-home.jpg",
  "bg": "bg/e8-cuemix-home.jpg",
  "product": "shared",
  "w": 2114,
  "h": 2062,
  "ar": 1.025,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (15).jpg"
  ]
 },
 {
  "slug": "e8-ess-logo",
  "file": "e8-ess-logo.jpg",
  "bg": "bg/e8-ess-logo.jpg",
  "product": "shared",
  "w": 1787,
  "h": 941,
  "ar": 1.899,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU 828 (19).jpg"
  ]
 },
 {
  "slug": "e8-fx-eq",
  "file": "e8-fx-eq.jpg",
  "bg": "bg/e8-fx-eq.jpg",
  "product": "shared",
  "w": 2160,
  "h": 1216,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (13).jpg"
  ]
 },
 {
  "slug": "e8-fx-gate",
  "file": "e8-fx-gate.jpg",
  "bg": "bg/e8-fx-gate.jpg",
  "product": "shared",
  "w": 2160,
  "h": 1216,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (12).jpg"
  ]
 },
 {
  "slug": "e8-fx-reverb",
  "file": "e8-fx-reverb.jpg",
  "bg": "bg/e8-fx-reverb.jpg",
  "product": "shared",
  "w": 2076,
  "h": 1169,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (16).jpg"
  ]
 },
 {
  "slug": "e8-mixer",
  "file": "e8-mixer.jpg",
  "bg": "bg/e8-mixer.jpg",
  "product": "shared",
  "w": 1542,
  "h": 1118,
  "ar": 1.379,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (14).jpg"
  ]
 },
 {
  "slug": "e8-mixer-phones",
  "file": "e8-mixer-phones.jpg",
  "bg": "bg/e8-mixer-phones.jpg",
  "product": "shared",
  "w": 2002,
  "h": 1282,
  "ar": 1.562,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (17).jpg"
  ]
 },
 {
  "slug": "e8-usb-5gbps",
  "file": "e8-usb-5gbps.jpg",
  "bg": "bg/e8-usb-5gbps.jpg",
  "product": "shared",
  "w": 1787,
  "h": 941,
  "ar": 1.899,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU 828 (31).jpg"
  ]
 },
 {
  "slug": "ul-cuemix-home",
  "file": "ul-cuemix-home.png",
  "bg": "bg/ul-cuemix-home.jpg",
  "product": "shared",
  "w": 2100,
  "h": 1948,
  "ar": 1.078,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (1).png"
  ]
 },
 {
  "slug": "ul-fx-eq",
  "file": "ul-fx-eq.jpg",
  "bg": "bg/ul-fx-eq.jpg",
  "product": "shared",
  "w": 1081,
  "h": 609,
  "ar": 1.775,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (7).jpg"
  ]
 },
 {
  "slug": "ul-fx-gate",
  "file": "ul-fx-gate.jpg",
  "bg": "bg/ul-fx-gate.jpg",
  "product": "shared",
  "w": 2160,
  "h": 1216,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (6).jpg"
  ]
 },
 {
  "slug": "ul-fx-reverb",
  "file": "ul-fx-reverb.jpg",
  "bg": "bg/ul-fx-reverb.jpg",
  "product": "shared",
  "w": 2160,
  "h": 1215,
  "ar": 1.778,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (9).jpg"
  ]
 },
 {
  "slug": "ul-mixer",
  "file": "ul-mixer.jpg",
  "bg": "bg/ul-mixer.jpg",
  "product": "shared",
  "w": 2153,
  "h": 1213,
  "ar": 1.775,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (8).jpg"
  ]
 }
];

export const REPO_FILE_COUNT = 69;
export const EXCLUDED_COUNT = 0;
