// AUTO-GENERATED by scripts/scan-higgsfield.mjs — do not edit by hand.
// Generated with Higgsfield (Nano Banana Pro stills from the real product
// photography as references; Kling 3.0 image-to-video B-roll from those stills).

export type HfStill = { id: string; file: string; bg: string; w: number; h: number; ar: number };
export type HfClip = { id: string; file: string; w: number; h: number; ar: number; seconds: number; fps: number };

export const HF_STILLS: HfStill[] = [
 {
  "id": "ul-desk",
  "file": "img-01-ul-desk.png",
  "bg": "bg/img-01-ul-desk.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "ul-road",
  "file": "img-02-ul-road.png",
  "bg": "bg/img-02-ul-road.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "ul-guitar",
  "file": "img-03-ul-guitar.png",
  "bg": "bg/img-03-ul-guitar.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "ul-stage",
  "file": "img-04-ul-stage.png",
  "bg": "bg/img-04-ul-stage.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "e8-control",
  "file": "img-05-e8-control.png",
  "bg": "bg/img-05-e8-control.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "e8-stream",
  "file": "img-06-e8-stream.png",
  "bg": "bg/img-06-e8-stream.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "e8-tracking",
  "file": "img-07-e8-tracking.png",
  "bg": "bg/img-07-e8-tracking.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "both-studio",
  "file": "img-08-both-studio.png",
  "bg": "bg/img-08-both-studio.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 }
];
export const HF_CLIPS: HfClip[] = [
 {
  "id": "ul-desk",
  "file": "clip-11-ul-desk.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "ul-road",
  "file": "clip-12-ul-road.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "ul-guitar",
  "file": "clip-13-ul-guitar.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "ul-stage",
  "file": "clip-14-ul-stage.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "e8-control",
  "file": "clip-15-e8-control.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "e8-stream",
  "file": "clip-16-e8-stream.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "e8-tracking",
  "file": "clip-17-e8-tracking.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "both-studio",
  "file": "clip-18-both-studio.mp4",
  "w": 1076,
  "h": 1928,
  "ar": 0.558,
  "seconds": 5.04,
  "fps": 24
 }
];

/** A still by id; portrait variants carry the same id with a "-9x16" suffix. */
export const still = (id: string): HfStill | undefined => HF_STILLS.find((s) => s.id === id);
export const clip = (id: string): HfClip | undefined => HF_CLIPS.find((c) => c.id === id);
