#!/usr/bin/env node
// Writes ../ASSET_COVERAGE_ULTRALITE_828_REEL.md from the same shot plan the
// reel renders from, so the ledger cannot drift from what is on screen.
// Run: node --experimental-strip-types scripts/coverage.mjs
import { writeFileSync } from "node:fs";
import { ASSETS, REPO_FILE_COUNT, EXCLUDED_COUNT } from "../src/assets.ts";
import { REEL_PINS, buildShots } from "../src/shots.ts";
import { REEL_TL } from "../src/script.ts";
import { REEL } from "../src/theme.ts";
import { HF_STILLS, HF_CLIPS } from "../src/higgsfield.ts";

const use = (tl, pins, canvas) => {
  const m = new Map();
  for (const s of buildShots(tl.segments, pins, canvas, tl.total + 0.6)) {
    const r = s.res;
    const list = r.kind === "bleed" || r.kind === "panel" ? [r.asset] : r.kind === "split" || r.kind === "mosaic" ? r.assets : [];
    for (const a of list) (m.get(a.slug) ?? m.set(a.slug, []).get(a.slug)).push(`${s.segment} @ ${s.start.toFixed(1)}s (${r.kind})`);
  }
  return m;
};
const reel = use(REEL_TL, REEL_PINS, REEL);
const both = new Set(reel.keys());

let md = `# ASSET COVERAGE — MOTU UltraLite-mk5 & 828, 90 s 4K reel

Generated by \`ultralite-828-reel/scripts/coverage.mjs\` from the shot plan the reel
renders from, so this ledger cannot drift from what is on screen. The inventory
is the ${ASSETS.length} distinct product photographs curated for this repository
(\`src/lib/images.json\`), re-exported here from the originals in the repository
root at up to 3840 px on the long edge.

| | Reel |
|---|---|
| Distinct real images on screen | **${reel.size} / ${ASSETS.length}** |

Total coverage is deliberately NOT a goal for a 90 s cut — the earlier 598 s
long-form and the 178 s reel pair in this repository already carry the 69/69
obligation between them. Here each photograph is chosen for the line it proves,
and the software screens are clubbed into one drifting mosaic. Generated
material: ${HF_STILLS.length} Higgsfield stills and ${HF_CLIPS.length} B-roll clips.

## Real images placed

| Image | Product | Subject | Where |
|---|---|---|---|
`;
for (const a of ASSETS) {
  if (!both.has(a.slug)) continue;
  md += `| \`${a.covers.join("`, `")}\` | ${a.product} | ${a.subject} | ${(reel.get(a.slug) ?? []).join("; ") || "—"} |\n`;
}
md += `\n## Real images not placed\n\n`;
for (const a of ASSETS) if (!both.has(a.slug)) md += `- \`${a.covers.join("`, `")}\` — ${a.subject}\n`;
md += `\n## Generated stills\n\n${HF_STILLS.map((s) => `- \`${s.file}\` ${s.w}×${s.h}`).join("\n")}\n\n## Generated B-roll\n\n${HF_CLIPS.map((c) => `- \`${c.file}\` ${c.w}×${c.h} · ${c.seconds}s`).join("\n")}\n`;
writeFileSync("../ASSET_COVERAGE_ULTRALITE_828_REEL.md", md);
console.log(`coverage: reel places ${reel.size}/${ASSETS.length} real images`);
