// Writes VOICEOVER-SCRIPT.md — the timestamped document to record against.
//
// Generated from the same timeline the picture is cut to, so a reader following
// these in and out points lands on the frame the shot was planned for.
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { VIDEO } from "../src/films.ts";
import { WPM, SEGMENT_GAP, BEAT, spokenWords } from "../src/script.ts";

const here = dirname(fileURLToPath(import.meta.url));
const ts = (s) => `${String(Math.floor(s / 60)).padStart(2, "0")}:${(s % 60).toFixed(2).padStart(5, "0")}`;

let md = `# MOTU M-Series — voiceover scripts

Both films, timestamped. Record against these in and out points and the picture
lands where it was planned: every shot is pinned to a caption, so the timing
below IS the edit.

Written to **${WPM} wpm**, with a **${SEGMENT_GAP}s** breath between chapters and a **${BEAT}s** beat
after a line that closes a thought. That lands at about 156 wpm effective — the
pace the AVB series and the UltraLite-mk5 / 828 films were read at.

Drop the recorded takes at \`public/vo/vo-reel.wav\` and \`public/vo/vo-video.wav\`
and re-render. Nothing else changes; both files are silent placeholders at
exactly the right length today.

> A word set in **bold** is the one the brush script carries on screen. Lean on it.

`;

for (const [title, film] of [["The five-minute landscape explainer", VIDEO]]) {
  md += `\n---\n\n## ${title}\n\n`;
  md += `**${film.words} words · ${film.speechEnd.toFixed(2)}s of speech · `;
  md += `${film.outroSeconds}s end screen · ${film.total.toFixed(2)}s total `;
  md += `(${film.durationInFrames} frames at 30 fps)**\n`;
  for (const seg of film.segments) {
    md += `\n### ${seg.chapter}\n\n`;
    md += `*${ts(seg.start)} – ${ts(seg.end)} · ${seg.words} words*\n\n`;
    for (const c of seg.captions) {
      const bold = c.t.replace(c.e, `**${c.e}**`);
      md += `- \`${ts(c.start)}\` ${bold}${c.beat ? "  *(beat)*" : ""}\n`;
    }
  }
  md += `\n\`${ts(film.speechEnd)}\` — **END SCREEN**, ${film.outroSeconds}s. No narration.\n`;
}

md += `\n---\n\nGenerated by \`scripts/script-doc.mjs\` from \`src/script.ts\`. Do not edit by hand —\nedit the script and re-run, or the picture and the voice will disagree.\n`;

writeFileSync(resolve(here, "..", "VOICEOVER-SCRIPT.md"), md);
console.log(`VOICEOVER-SCRIPT.md: ${VIDEO.words} words`);
