// AUTO-GENERATED by scripts/prep-assets.mjs — do not edit by hand.
// 69 distinct images from 69 files in the repository root.
// kind:    cutout (transparent) | strip (transparent ultra-wide) | panel (opaque ultra-wide) | photo
// subject: hardware | detail | context | ui | diagram | mark | bundle

export type AssetKind = "cutout" | "strip" | "panel" | "photo";
export type AssetSubject = "hardware" | "detail" | "context" | "ui" | "diagram" | "mark" | "bundle";
export type ProductKey = "pmk5" | "p828" | "shared";

export type Asset = {
  slug: string; file: string; bg: string; product: ProductKey;
  w: number; h: number; ar: number; kind: AssetKind; subject: AssetSubject; alpha: boolean; covers: string[];
};

export const ASSETS: Asset[] = [
 {
  "slug": "motu-828-1-jpg",
  "file": "motu-828-1-jpg.jpg",
  "bg": "bg/motu-828-1-jpg.jpg",
  "product": "p828",
  "w": 2000,
  "h": 891,
  "ar": 2.245,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (1).jpg"
  ]
 },
 {
  "slug": "motu-828-1-png",
  "file": "motu-828-1-png.png",
  "bg": "bg/motu-828-1-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 733,
  "ar": 4.093,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (1).png"
  ]
 },
 {
  "slug": "motu-828-10-jpg",
  "file": "motu-828-10-jpg.jpg",
  "bg": "bg/motu-828-10-jpg.jpg",
  "product": "p828",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (10).jpg"
  ]
 },
 {
  "slug": "motu-828-12-jpg",
  "file": "motu-828-12-jpg.jpg",
  "bg": "bg/motu-828-12-jpg.jpg",
  "product": "p828",
  "w": 2160,
  "h": 1216,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (12).jpg"
  ]
 },
 {
  "slug": "motu-828-13-jpg",
  "file": "motu-828-13-jpg.jpg",
  "bg": "bg/motu-828-13-jpg.jpg",
  "product": "p828",
  "w": 2160,
  "h": 1216,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (13).jpg"
  ]
 },
 {
  "slug": "motu-828-13-png",
  "file": "motu-828-13-png.png",
  "bg": "bg/motu-828-13-png.jpg",
  "product": "p828",
  "w": 1900,
  "h": 821,
  "ar": 2.314,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (13).png"
  ]
 },
 {
  "slug": "motu-828-14-jpg",
  "file": "motu-828-14-jpg.jpg",
  "bg": "bg/motu-828-14-jpg.jpg",
  "product": "p828",
  "w": 1542,
  "h": 1118,
  "ar": 1.379,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (14).jpg"
  ]
 },
 {
  "slug": "motu-828-14-png",
  "file": "motu-828-14-png.png",
  "bg": "bg/motu-828-14-png.jpg",
  "product": "p828",
  "w": 815,
  "h": 276,
  "ar": 2.953,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 828 (14).png"
  ]
 },
 {
  "slug": "motu-828-15-jpg",
  "file": "motu-828-15-jpg.jpg",
  "bg": "bg/motu-828-15-jpg.jpg",
  "product": "p828",
  "w": 2114,
  "h": 2062,
  "ar": 1.025,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (15).jpg"
  ]
 },
 {
  "slug": "motu-828-15-png",
  "file": "motu-828-15-png.png",
  "bg": "bg/motu-828-15-png.jpg",
  "product": "p828",
  "w": 948,
  "h": 512,
  "ar": 1.852,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU 828 (15).png"
  ]
 },
 {
  "slug": "motu-828-16-jpg",
  "file": "motu-828-16-jpg.jpg",
  "bg": "bg/motu-828-16-jpg.jpg",
  "product": "p828",
  "w": 2076,
  "h": 1169,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (16).jpg"
  ]
 },
 {
  "slug": "motu-828-17-jpg",
  "file": "motu-828-17-jpg.jpg",
  "bg": "bg/motu-828-17-jpg.jpg",
  "product": "p828",
  "w": 2002,
  "h": 1282,
  "ar": 1.562,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (17).jpg"
  ]
 },
 {
  "slug": "motu-828-18-jpg",
  "file": "motu-828-18-jpg.jpg",
  "bg": "bg/motu-828-18-jpg.jpg",
  "product": "p828",
  "w": 2500,
  "h": 1732,
  "ar": 1.443,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (18).jpg"
  ]
 },
 {
  "slug": "motu-828-2-jpg",
  "file": "motu-828-2-jpg.jpg",
  "bg": "bg/motu-828-2-jpg.jpg",
  "product": "p828",
  "w": 768,
  "h": 768,
  "ar": 1,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (2).jpg"
  ]
 },
 {
  "slug": "motu-828-2-png",
  "file": "motu-828-2-png.png",
  "bg": "bg/motu-828-2-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 769,
  "ar": 3.901,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (2).png"
  ]
 },
 {
  "slug": "motu-828-20-jpg",
  "file": "motu-828-20-jpg.jpg",
  "bg": "bg/motu-828-20-jpg.jpg",
  "product": "p828",
  "w": 509,
  "h": 417,
  "ar": 1.221,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (20).jpg"
  ]
 },
 {
  "slug": "motu-828-21-jpg",
  "file": "motu-828-21-jpg.jpg",
  "bg": "bg/motu-828-21-jpg.jpg",
  "product": "p828",
  "w": 3000,
  "h": 1384,
  "ar": 2.168,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (21).jpg"
  ]
 },
 {
  "slug": "motu-828-22-jpg",
  "file": "motu-828-22-jpg.jpg",
  "bg": "bg/motu-828-22-jpg.jpg",
  "product": "p828",
  "w": 1038,
  "h": 629,
  "ar": 1.65,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (22).jpg"
  ]
 },
 {
  "slug": "motu-828-25-jpg",
  "file": "motu-828-25-jpg.jpg",
  "bg": "bg/motu-828-25-jpg.jpg",
  "product": "p828",
  "w": 2000,
  "h": 1029,
  "ar": 1.944,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (25).jpg"
  ]
 },
 {
  "slug": "motu-828-27-jpg",
  "file": "motu-828-27-jpg.jpg",
  "bg": "bg/motu-828-27-jpg.jpg",
  "product": "p828",
  "w": 2000,
  "h": 714,
  "ar": 2.801,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 828 (27).jpg"
  ]
 },
 {
  "slug": "motu-828-28-jpg",
  "file": "motu-828-28-jpg.jpg",
  "bg": "bg/motu-828-28-jpg.jpg",
  "product": "p828",
  "w": 2509,
  "h": 2166,
  "ar": 1.158,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (28).jpg"
  ]
 },
 {
  "slug": "motu-828-3-jpg",
  "file": "motu-828-3-jpg.jpg",
  "bg": "bg/motu-828-3-jpg.jpg",
  "product": "p828",
  "w": 1522,
  "h": 485,
  "ar": 3.138,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (3).jpg"
  ]
 },
 {
  "slug": "motu-828-3-png",
  "file": "motu-828-3-png.png",
  "bg": "bg/motu-828-3-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 465,
  "ar": 6.452,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (3).png"
  ]
 },
 {
  "slug": "motu-828-30-jpg",
  "file": "motu-828-30-jpg.jpg",
  "bg": "bg/motu-828-30-jpg.jpg",
  "product": "p828",
  "w": 1000,
  "h": 519,
  "ar": 1.927,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (30).jpg"
  ]
 },
 {
  "slug": "motu-828-31-jpg",
  "file": "motu-828-31-jpg.jpg",
  "bg": "bg/motu-828-31-jpg.jpg",
  "product": "p828",
  "w": 1787,
  "h": 941,
  "ar": 1.899,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU 828 (31).jpg"
  ]
 },
 {
  "slug": "motu-828-4-jpg",
  "file": "motu-828-4-jpg.jpg",
  "bg": "bg/motu-828-4-jpg.jpg",
  "product": "p828",
  "w": 768,
  "h": 456,
  "ar": 1.684,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (4).jpg"
  ]
 },
 {
  "slug": "motu-828-4-png",
  "file": "motu-828-4-png.png",
  "bg": "bg/motu-828-4-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 272,
  "ar": 11.029,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (4).png"
  ]
 },
 {
  "slug": "motu-828-5-jpg",
  "file": "motu-828-5-jpg.jpg",
  "bg": "bg/motu-828-5-jpg.jpg",
  "product": "p828",
  "w": 576,
  "h": 497,
  "ar": 1.159,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (5).jpg"
  ]
 },
 {
  "slug": "motu-828-5-png",
  "file": "motu-828-5-png.png",
  "bg": "bg/motu-828-5-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 717,
  "ar": 4.184,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (5).png"
  ]
 },
 {
  "slug": "motu-828-6-jpg",
  "file": "motu-828-6-jpg.jpg",
  "bg": "bg/motu-828-6-jpg.jpg",
  "product": "p828",
  "w": 3000,
  "h": 1366,
  "ar": 2.196,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 828 (6).jpg"
  ]
 },
 {
  "slug": "motu-828-6-png",
  "file": "motu-828-6-png.png",
  "bg": "bg/motu-828-6-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 746,
  "ar": 4.021,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (6).png"
  ]
 },
 {
  "slug": "motu-828-7-jpg",
  "file": "motu-828-7-jpg.jpg",
  "bg": "bg/motu-828-7-jpg.jpg",
  "product": "p828",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (7).jpg"
  ]
 },
 {
  "slug": "motu-828-7-png",
  "file": "motu-828-7-png.png",
  "bg": "bg/motu-828-7-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 505,
  "ar": 5.941,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (7).png"
  ]
 },
 {
  "slug": "motu-828-8-png",
  "file": "motu-828-8-png.png",
  "bg": "bg/motu-828-8-png.jpg",
  "product": "p828",
  "w": 3000,
  "h": 298,
  "ar": 10.067,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 828 (8).png"
  ]
 },
 {
  "slug": "motu-828-9-jpg",
  "file": "motu-828-9-jpg.jpg",
  "bg": "bg/motu-828-9-jpg.jpg",
  "product": "p828",
  "w": 423,
  "h": 481,
  "ar": 0.879,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 828 (9).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-1-jpg",
  "file": "motu-ultralite-mk5-1-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-1-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 2066,
  "ar": 1.452,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (1).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-1-png",
  "file": "motu-ultralite-mk5-1-png.png",
  "bg": "bg/motu-ultralite-mk5-1-png.jpg",
  "product": "pmk5",
  "w": 2100,
  "h": 1948,
  "ar": 1.078,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (1).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-10-jpg",
  "file": "motu-ultralite-mk5-10-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-10-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 2066,
  "ar": 1.452,
  "kind": "photo",
  "subject": "diagram",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (10).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-11-jpg",
  "file": "motu-ultralite-mk5-11-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-11-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1826,
  "ar": 1.643,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (11).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-12-jpg",
  "file": "motu-ultralite-mk5-12-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-12-jpg.jpg",
  "product": "pmk5",
  "w": 2560,
  "h": 1656,
  "ar": 1.546,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (12).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-13-jpg",
  "file": "motu-ultralite-mk5-13-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-13-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1928,
  "ar": 1.556,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (13).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-14-jpg",
  "file": "motu-ultralite-mk5-14-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-14-jpg.jpg",
  "product": "pmk5",
  "w": 1726,
  "h": 835,
  "ar": 2.067,
  "kind": "photo",
  "subject": "diagram",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (14).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-2-jpg",
  "file": "motu-ultralite-mk5-2-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-2-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1826,
  "ar": 1.643,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (2).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-2-png",
  "file": "motu-ultralite-mk5-2-png.png",
  "bg": "bg/motu-ultralite-mk5-2-png.jpg",
  "product": "pmk5",
  "w": 2200,
  "h": 1000,
  "ar": 2.2,
  "kind": "cutout",
  "subject": "detail",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (2).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-3-jpg",
  "file": "motu-ultralite-mk5-3-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-3-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1942,
  "ar": 1.545,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (3).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-3-png",
  "file": "motu-ultralite-mk5-3-png.png",
  "bg": "bg/motu-ultralite-mk5-3-png.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1690,
  "ar": 1.775,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (3).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-4-jpg",
  "file": "motu-ultralite-mk5-4-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-4-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1788,
  "ar": 1.678,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (4).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-4-png",
  "file": "motu-ultralite-mk5-4-png.png",
  "bg": "bg/motu-ultralite-mk5-4-png.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 2100,
  "ar": 1.429,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (4).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-5-jpg",
  "file": "motu-ultralite-mk5-5-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-5-jpg.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 2004,
  "ar": 1.497,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (5).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-5-png",
  "file": "motu-ultralite-mk5-5-png.png",
  "bg": "bg/motu-ultralite-mk5-5-png.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 2100,
  "ar": 1.429,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (5).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-6-jpg",
  "file": "motu-ultralite-mk5-6-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-6-jpg.jpg",
  "product": "pmk5",
  "w": 2160,
  "h": 1216,
  "ar": 1.776,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (6).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-6-png",
  "file": "motu-ultralite-mk5-6-png.png",
  "bg": "bg/motu-ultralite-mk5-6-png.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1538,
  "ar": 1.951,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (6).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-7-jpg",
  "file": "motu-ultralite-mk5-7-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-7-jpg.jpg",
  "product": "pmk5",
  "w": 1081,
  "h": 609,
  "ar": 1.775,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (7).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-7-png",
  "file": "motu-ultralite-mk5-7-png.png",
  "bg": "bg/motu-ultralite-mk5-7-png.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 1876,
  "ar": 1.599,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (7).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-8-jpg",
  "file": "motu-ultralite-mk5-8-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-8-jpg.jpg",
  "product": "pmk5",
  "w": 2153,
  "h": 1213,
  "ar": 1.775,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (8).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-8-png",
  "file": "motu-ultralite-mk5-8-png.png",
  "bg": "bg/motu-ultralite-mk5-8-png.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 592,
  "ar": 5.068,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (8).png"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-9-jpg",
  "file": "motu-ultralite-mk5-9-jpg.jpg",
  "bg": "bg/motu-ultralite-mk5-9-jpg.jpg",
  "product": "pmk5",
  "w": 2160,
  "h": 1215,
  "ar": 1.778,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU UltraLite-mk5 (9).jpg"
  ]
 },
 {
  "slug": "motu-ultralite-mk5-9-png",
  "file": "motu-ultralite-mk5-9-png.png",
  "bg": "bg/motu-ultralite-mk5-9-png.jpg",
  "product": "pmk5",
  "w": 3000,
  "h": 594,
  "ar": 5.051,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU UltraLite-mk5 (9).png"
  ]
 },
 {
  "slug": "motu-828-10-png",
  "file": "motu-828-10-png.png",
  "bg": "bg/motu-828-10-png.jpg",
  "product": "shared",
  "w": 1678,
  "h": 948,
  "ar": 1.77,
  "kind": "cutout",
  "subject": "bundle",
  "alpha": true,
  "covers": [
   "MOTU 828 (10).png"
  ]
 },
 {
  "slug": "motu-828-11-jpg",
  "file": "motu-828-11-jpg.jpg",
  "bg": "bg/motu-828-11-jpg.jpg",
  "product": "shared",
  "w": 2000,
  "h": 1532,
  "ar": 1.305,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (11).jpg"
  ]
 },
 {
  "slug": "motu-828-11-png",
  "file": "motu-828-11-png.png",
  "bg": "bg/motu-828-11-png.jpg",
  "product": "shared",
  "w": 2562,
  "h": 1513,
  "ar": 1.693,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU 828 (11).png"
  ]
 },
 {
  "slug": "motu-828-12-png",
  "file": "motu-828-12-png.png",
  "bg": "bg/motu-828-12-png.jpg",
  "product": "shared",
  "w": 2880,
  "h": 1711,
  "ar": 1.683,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU 828 (12).png"
  ]
 },
 {
  "slug": "motu-828-19-jpg",
  "file": "motu-828-19-jpg.jpg",
  "bg": "bg/motu-828-19-jpg.jpg",
  "product": "shared",
  "w": 1787,
  "h": 941,
  "ar": 1.899,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU 828 (19).jpg"
  ]
 },
 {
  "slug": "motu-828-23-jpg",
  "file": "motu-828-23-jpg.jpg",
  "bg": "bg/motu-828-23-jpg.jpg",
  "product": "shared",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (23).jpg"
  ]
 },
 {
  "slug": "motu-828-24-jpg",
  "file": "motu-828-24-jpg.jpg",
  "bg": "bg/motu-828-24-jpg.jpg",
  "product": "shared",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (24).jpg"
  ]
 },
 {
  "slug": "motu-828-26-jpg",
  "file": "motu-828-26-jpg.jpg",
  "bg": "bg/motu-828-26-jpg.jpg",
  "product": "shared",
  "w": 576,
  "h": 425,
  "ar": 1.355,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 828 (26).jpg"
  ]
 },
 {
  "slug": "motu-828-29-jpg",
  "file": "motu-828-29-jpg.jpg",
  "bg": "bg/motu-828-29-jpg.jpg",
  "product": "shared",
  "w": 2880,
  "h": 834,
  "ar": 3.453,
  "kind": "panel",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (29).jpg"
  ]
 },
 {
  "slug": "motu-828-8-jpg",
  "file": "motu-828-8-jpg.jpg",
  "bg": "bg/motu-828-8-jpg.jpg",
  "product": "shared",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 828 (8).jpg"
  ]
 },
 {
  "slug": "motu-828-9-png",
  "file": "motu-828-9-png.png",
  "bg": "bg/motu-828-9-png.jpg",
  "product": "shared",
  "w": 1024,
  "h": 1024,
  "ar": 1,
  "kind": "cutout",
  "subject": "mark",
  "alpha": true,
  "covers": [
   "MOTU 828 (9).png"
  ]
 }
];

export const REPO_FILE_COUNT = 69;
export const EXCLUDED_COUNT = 0;
