// AUTO-GENERATED by scripts/scan-higgsfield.mjs — do not edit by hand.
// Generated with Higgsfield (Nano Banana Pro stills from the real product
// photography as references; Kling 3.0 image-to-video B-roll from those stills).

export type HfStill = { id: string; file: string; bg: string; w: number; h: number; ar: number };
export type HfClip = { id: string; file: string; w: number; h: number; ar: number; seconds: number; fps: number };

export const HF_STILLS: HfStill[] = [];
export const HF_CLIPS: HfClip[] = [];

/** A still by id; portrait variants carry the same id with a "-9x16" suffix. */
export const still = (id: string): HfStill | undefined => HF_STILLS.find((s) => s.id === id);
export const clip = (id: string): HfClip | undefined => HF_CLIPS.find((c) => c.id === id);
