#!/usr/bin/env node
// Writes ../ASSET_COVERAGE_AVB_SERIES_FILM.md from the same shot plans the
// films render from, so the ledger cannot drift from what is on screen.
// Run: node --experimental-strip-types scripts/coverage.mjs
import { writeFileSync } from "node:fs";
import { ASSETS, REPO_FILE_COUNT, EXCLUDED_COUNT } from "../src/assets.ts";
import { REEL_PINS, FILM_PINS, buildShots } from "../src/shots.ts";
import { REEL_TL, FILM_TL } from "../src/script.ts";
import { REEL, FILM } from "../src/theme.ts";
import { HF_STILLS, HF_CLIPS } from "../src/higgsfield.ts";

const use = (tl, pins, canvas) => {
  const m = new Map();
  for (const s of buildShots(tl.segments, pins, canvas, tl.total + 0.6)) {
    const r = s.res;
    const list = r.kind === "bleed" || r.kind === "panel" ? [r.asset] : r.kind === "split" || r.kind === "mosaic" ? r.assets : [];
    for (const a of list) (m.get(a.slug) ?? m.set(a.slug, []).get(a.slug)).push(`${s.segment} @ ${s.start.toFixed(1)}s (${r.kind})`);
  }
  return m;
};
const reel = use(REEL_TL, REEL_PINS, REEL);
const film = use(FILM_TL, FILM_PINS, FILM);
const both = new Set([...reel.keys(), ...film.keys()]);

let md = `# ASSET COVERAGE — MOTU AVB Series reel + film

Generated by \`avb-series-film/scripts/coverage.mjs\` from the shot plans the films
render from. ${REPO_FILE_COUNT} product filenames in the repository root are
${ASSETS.length} distinct images (${REPO_FILE_COUNT - ASSETS.length - EXCLUDED_COUNT} byte-identical duplicates collapsed,
${EXCLUDED_COUNT} content-excluded: the Moog photograph and the blank grey PNG).

| | Reel | Film | Either |
|---|---|---|---|
| Distinct real images on screen | ${reel.size} | ${film.size} | **${both.size} / ${ASSETS.length}** |

Coverage of every image was not a requirement for this build; the software
screens are clubbed into mosaics and the product photography is chosen for the
line it proves. Generated material: ${HF_STILLS.length} Higgsfield stills and ${HF_CLIPS.length} B-roll clips.

## Real images placed

| Image | Product | Subject | Reel | Film |
|---|---|---|---|---|
`;
for (const a of ASSETS) {
  if (!both.has(a.slug)) continue;
  md += `| \`${a.covers.join("`, `")}\` | ${a.product} | ${a.subject} | ${(reel.get(a.slug) ?? []).join("; ") || "—"} | ${(film.get(a.slug) ?? []).join("; ") || "—"} |\n`;
}
md += `\n## Real images not placed\n\n`;
for (const a of ASSETS) if (!both.has(a.slug)) md += `- \`${a.covers.join("`, `")}\` — ${a.subject}\n`;
md += `\n## Generated stills\n\n${HF_STILLS.map((s) => `- \`${s.file}\` ${s.w}×${s.h}`).join("\n")}\n\n## Generated B-roll\n\n${HF_CLIPS.map((c) => `- \`${c.file}\` ${c.w}×${c.h} · ${c.seconds}s`).join("\n")}\n`;
writeFileSync("../ASSET_COVERAGE_AVB_SERIES_FILM.md", md);
console.log(`coverage: reel ${reel.size}, film ${film.size}, either ${both.size}/${ASSETS.length}`);
