/**
 * The complete raw-photography inventory for this reel, generated by
 * `tools/make_images_ts.py` from the numbered source files at the repository
 * root. 69 distinct images: 46 for the MOTU 828, 23 for the UltraLite-mk5.
 *
 * The same-numbered .jpg and .png at the repo root are NOT two encodings of one
 * shot - they are different pictures (UltraLite (1).jpg is a lifestyle photo,
 * UltraLite (1).png is a software screen). That was verified image-by-image
 * before this list was built, which is why the count is 69 and not 45.
 *
 * `cutout` marks a PNG whose subject is masked against transparency, so it can
 * be laid straight onto the paper as a collage object instead of inside a card.
 */
export type ImgMeta = {slug: string; file: string; w: number; h: number; product: 'ul' | 'e828'; cutout: boolean};

export const IMAGES: Record<string, ImgMeta> = {
  e828_01j: {slug: 'e828_01j', file: 'e828_01j.jpg', w: 2000, h: 891, product: 'e828', cutout: false},
  e828_01p: {slug: 'e828_01p', file: 'e828_01p.png', w: 3000, h: 733, product: 'e828', cutout: true},
  e828_02j: {slug: 'e828_02j', file: 'e828_02j.jpg', w: 768, h: 768, product: 'e828', cutout: false},
  e828_02p: {slug: 'e828_02p', file: 'e828_02p.png', w: 3000, h: 769, product: 'e828', cutout: true},
  e828_03j: {slug: 'e828_03j', file: 'e828_03j.jpg', w: 1522, h: 485, product: 'e828', cutout: false},
  e828_03p: {slug: 'e828_03p', file: 'e828_03p.png', w: 3000, h: 465, product: 'e828', cutout: true},
  e828_04j: {slug: 'e828_04j', file: 'e828_04j.jpg', w: 768, h: 456, product: 'e828', cutout: false},
  e828_04p: {slug: 'e828_04p', file: 'e828_04p.png', w: 3000, h: 272, product: 'e828', cutout: false},
  e828_05j: {slug: 'e828_05j', file: 'e828_05j.jpg', w: 576, h: 497, product: 'e828', cutout: false},
  e828_05p: {slug: 'e828_05p', file: 'e828_05p.png', w: 3000, h: 717, product: 'e828', cutout: true},
  e828_06j: {slug: 'e828_06j', file: 'e828_06j.jpg', w: 3200, h: 1458, product: 'e828', cutout: false},
  e828_06p: {slug: 'e828_06p', file: 'e828_06p.png', w: 3000, h: 746, product: 'e828', cutout: true},
  e828_07j: {slug: 'e828_07j', file: 'e828_07j.jpg', w: 2000, h: 1083, product: 'e828', cutout: false},
  e828_07p: {slug: 'e828_07p', file: 'e828_07p.png', w: 3000, h: 505, product: 'e828', cutout: true},
  e828_08j: {slug: 'e828_08j', file: 'e828_08j.jpg', w: 1149, h: 1186, product: 'e828', cutout: false},
  e828_08p: {slug: 'e828_08p', file: 'e828_08p.png', w: 3000, h: 298, product: 'e828', cutout: false},
  e828_09j: {slug: 'e828_09j', file: 'e828_09j.jpg', w: 423, h: 481, product: 'e828', cutout: false},
  e828_09p: {slug: 'e828_09p', file: 'e828_09p.png', w: 1024, h: 1024, product: 'e828', cutout: true},
  e828_10j: {slug: 'e828_10j', file: 'e828_10j.jpg', w: 2000, h: 1083, product: 'e828', cutout: false},
  e828_10p: {slug: 'e828_10p', file: 'e828_10p.png', w: 1678, h: 948, product: 'e828', cutout: true},
  e828_11j: {slug: 'e828_11j', file: 'e828_11j.jpg', w: 2000, h: 1532, product: 'e828', cutout: false},
  e828_11p: {slug: 'e828_11p', file: 'e828_11p.png', w: 2562, h: 1513, product: 'e828', cutout: false},
  e828_12j: {slug: 'e828_12j', file: 'e828_12j.jpg', w: 2160, h: 1216, product: 'e828', cutout: false},
  e828_12p: {slug: 'e828_12p', file: 'e828_12p.png', w: 2880, h: 1711, product: 'e828', cutout: false},
  e828_13j: {slug: 'e828_13j', file: 'e828_13j.jpg', w: 2160, h: 1216, product: 'e828', cutout: false},
  e828_13p: {slug: 'e828_13p', file: 'e828_13p.png', w: 1900, h: 821, product: 'e828', cutout: false},
  e828_14j: {slug: 'e828_14j', file: 'e828_14j.jpg', w: 1542, h: 1118, product: 'e828', cutout: false},
  e828_14p: {slug: 'e828_14p', file: 'e828_14p.png', w: 815, h: 276, product: 'e828', cutout: false},
  e828_15j: {slug: 'e828_15j', file: 'e828_15j.jpg', w: 2114, h: 2062, product: 'e828', cutout: false},
  e828_15p: {slug: 'e828_15p', file: 'e828_15p.png', w: 948, h: 512, product: 'e828', cutout: false},
  e828_16j: {slug: 'e828_16j', file: 'e828_16j.jpg', w: 2076, h: 1169, product: 'e828', cutout: false},
  e828_17j: {slug: 'e828_17j', file: 'e828_17j.jpg', w: 2002, h: 1282, product: 'e828', cutout: false},
  e828_18j: {slug: 'e828_18j', file: 'e828_18j.jpg', w: 2500, h: 1732, product: 'e828', cutout: false},
  e828_19j: {slug: 'e828_19j', file: 'e828_19j.jpg', w: 1787, h: 941, product: 'e828', cutout: false},
  e828_20j: {slug: 'e828_20j', file: 'e828_20j.jpg', w: 509, h: 417, product: 'e828', cutout: false},
  e828_21j: {slug: 'e828_21j', file: 'e828_21j.jpg', w: 3200, h: 1476, product: 'e828', cutout: false},
  e828_22j: {slug: 'e828_22j', file: 'e828_22j.jpg', w: 1038, h: 629, product: 'e828', cutout: false},
  e828_23j: {slug: 'e828_23j', file: 'e828_23j.jpg', w: 1149, h: 1186, product: 'e828', cutout: false},
  e828_24j: {slug: 'e828_24j', file: 'e828_24j.jpg', w: 1149, h: 1186, product: 'e828', cutout: false},
  e828_25j: {slug: 'e828_25j', file: 'e828_25j.jpg', w: 2000, h: 1029, product: 'e828', cutout: false},
  e828_26j: {slug: 'e828_26j', file: 'e828_26j.jpg', w: 576, h: 425, product: 'e828', cutout: false},
  e828_27j: {slug: 'e828_27j', file: 'e828_27j.jpg', w: 2000, h: 714, product: 'e828', cutout: false},
  e828_28j: {slug: 'e828_28j', file: 'e828_28j.jpg', w: 2509, h: 2166, product: 'e828', cutout: false},
  e828_29j: {slug: 'e828_29j', file: 'e828_29j.jpg', w: 2880, h: 834, product: 'e828', cutout: false},
  e828_30j: {slug: 'e828_30j', file: 'e828_30j.jpg', w: 1000, h: 519, product: 'e828', cutout: false},
  e828_31j: {slug: 'e828_31j', file: 'e828_31j.jpg', w: 1787, h: 941, product: 'e828', cutout: false},
  ul_01j: {slug: 'ul_01j', file: 'ul_01j.jpg', w: 3200, h: 2204, product: 'ul', cutout: false},
  ul_01p: {slug: 'ul_01p', file: 'ul_01p.png', w: 2100, h: 1948, product: 'ul', cutout: true},
  ul_02j: {slug: 'ul_02j', file: 'ul_02j.jpg', w: 3200, h: 1947, product: 'ul', cutout: false},
  ul_02p: {slug: 'ul_02p', file: 'ul_02p.png', w: 2200, h: 1000, product: 'ul', cutout: false},
  ul_03j: {slug: 'ul_03j', file: 'ul_03j.jpg', w: 3200, h: 2070, product: 'ul', cutout: false},
  ul_03p: {slug: 'ul_03p', file: 'ul_03p.png', w: 3200, h: 1803, product: 'ul', cutout: true},
  ul_04j: {slug: 'ul_04j', file: 'ul_04j.jpg', w: 3200, h: 1908, product: 'ul', cutout: false},
  ul_04p: {slug: 'ul_04p', file: 'ul_04p.png', w: 3200, h: 2240, product: 'ul', cutout: true},
  ul_05j: {slug: 'ul_05j', file: 'ul_05j.jpg', w: 3200, h: 2138, product: 'ul', cutout: false},
  ul_05p: {slug: 'ul_05p', file: 'ul_05p.png', w: 3200, h: 2240, product: 'ul', cutout: true},
  ul_06j: {slug: 'ul_06j', file: 'ul_06j.jpg', w: 2160, h: 1216, product: 'ul', cutout: false},
  ul_06p: {slug: 'ul_06p', file: 'ul_06p.png', w: 3200, h: 1641, product: 'ul', cutout: true},
  ul_07j: {slug: 'ul_07j', file: 'ul_07j.jpg', w: 1081, h: 609, product: 'ul', cutout: false},
  ul_07p: {slug: 'ul_07p', file: 'ul_07p.png', w: 3200, h: 2001, product: 'ul', cutout: true},
  ul_08j: {slug: 'ul_08j', file: 'ul_08j.jpg', w: 2153, h: 1213, product: 'ul', cutout: false},
  ul_08p: {slug: 'ul_08p', file: 'ul_08p.png', w: 3200, h: 631, product: 'ul', cutout: false},
  ul_09j: {slug: 'ul_09j', file: 'ul_09j.jpg', w: 2160, h: 1215, product: 'ul', cutout: false},
  ul_09p: {slug: 'ul_09p', file: 'ul_09p.png', w: 3200, h: 634, product: 'ul', cutout: false},
  ul_10j: {slug: 'ul_10j', file: 'ul_10j.jpg', w: 3200, h: 2203, product: 'ul', cutout: false},
  ul_11j: {slug: 'ul_11j', file: 'ul_11j.jpg', w: 3200, h: 1947, product: 'ul', cutout: false},
  ul_12j: {slug: 'ul_12j', file: 'ul_12j.jpg', w: 2560, h: 1656, product: 'ul', cutout: false},
  ul_13j: {slug: 'ul_13j', file: 'ul_13j.jpg', w: 3200, h: 2057, product: 'ul', cutout: false},
  ul_14j: {slug: 'ul_14j', file: 'ul_14j.jpg', w: 1726, h: 835, product: 'ul', cutout: false},
};

export const ALL_SLUGS = Object.keys(IMAGES);
